apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::308731954939:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-0zayIVQGMbvl
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::308731954939:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-17T12:15:02Z"
  name: aws-auth
  namespace: kube-system
  